export ZSH="$HOME/.oh-my-zsh"
#ZSH_THEME="robbyrussell"
ZSH_THEME="itchy"
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Path
export PATH="/bin:/usr/bin:/home/r3b3l/go/bin/:/home/r3b3l/.cargo/bin/:/home/r3b3l/.local/bin"

# Personal Aliases
alias cat="bat"
alias catt="/bin/cat"
alias dl="cd ~/Downloads"
alias doc="cd ~/Documents"
alias masluz="brightnessctl set +2%"
alias menosluz="brightnessctl set 2%-"
alias wow="wine64 ~/Documents/wow/Wow.exe"
alias minecraftplus="java -jar ~/Documents/minecraft/TLauncher-2.895.jar; echo starting server... ; cd ~/Documents/minecraft;  java -jar ~/Documents/minecraft/server.jar nogui"
alias minecraft="java -jar ~/Documents/minecraft/TLauncher-2.895.jar"
alias screen="bash ~/Documents/7h3r3b3l/scripts/screen.sh"
alias single="bash ~/Documents/7h3r3b3l/scripts/single.sh"
# Termbin for http://termbin.com/
alias termbin="nc termbin.com 9999"
#alias protonvpn="sudo openvpn --config ~/Documents/nl_proton.ovpn --auth-user-pass ~/.protonvpn.txt"
alias change_wallpaper="bash ~/Documents/7h3r3b3l/scripts/change_wallpaper.sh; echo wallpaper changed for the next reboot"

# Local Playlists
alias hack="mpv -shuffle  ~/Music/Hack/*"
alias deephack="mpv -shuffle ~/Music/DeepHack/*"
alias music="mpv -shuffle  ~/Music/Musica_Toda/*"
# Radios
alias radio_defcon="mpv -cache 10000 -cache-min 0 https://ice2.somafm.com/defcon-128-mp3"
alias radio_boleros="mpv -cache 10000 -cache-min 0 'https://stream-159.zeno.fm/5t45zksv7mruv?zs=FpFDWpluQo6NxWwCXZTPNA'"
alias radio_heavyweight_reggae="mpv -cache 10000 -cache-min 0 'https://ice5.somafm.com/reggae-128-mp3'"
alias radio_groove_salad="mpv -cache 10000 -cache-min 0 'https://ice5.somafm.com/gsclassic-128-mp3'"
alias radio_underground_80s="mpv -cache 10000 -cache-min 0 'https://ice2.somafm.com/u80s-128-mp3'"
alias radio_tango="mpv -cache 10000 -cache-min 0 'http://server.laradio.online:8254/;'"
alias radio_argentina_tango="mpv -cache 10000 -cache-min 0 'http://server.laradio.online:8254/;'"
alias radio_rc_tango="mpv -cache 10000 -cache-min 0 'http://79.120.39.202:8002/tango'"
alias radio_rc_gangstarap="mpv -cache 10000 -cache-min 0 'http://79.120.39.202:8002/gangstarap'"
alias radio_rc_chicanorap="mpv -cache 10000 -cache-min 0 'http://213.141.131.10:8002/chicanorap'"
alias radio_rc_jazzrap="mpv -cache 10000 -cache-min 0 'http://79.120.39.202:8002/jazzrap'"
alias radio_rc_classical_minimalist="mpv -cache 10000 -cache-min 0 'http://213.141.131.10:8002/minimalism'"
alias radio_rc_classical_baroque="mpv -cache 10000 -cache-min 0 'http://79.111.14.76:8002/baroque'"
alias radio_rc_classical_contemporary="mpv -cache 10000 -cache-min 0 'http://79.111.119.111:8002/contclass'"
alias radio_rc_classical_impressionism="mpv -cache 10000 -cache-min 0 'http://79.120.12.130:8002/impressionism'"
alias radio_rc_classical_guitar="mpv -cache 10000 -cache-min 0 'http://213.141.131.10:8002/classguitar'"
alias radio_rc_relax="mpv -cache 10000 -cache-min 0 'http://79.120.39.202:8000/relaxation'"
alias radio_rc_modal_jazz="mpv -cache 10000 -cache-min 0 'http://213.141.131.10:8002/modaljazz'"
alias radio_rc_jazz_noir="mpv -cache 10000 -cache-min 0 'http://79.120.39.202:8002/darkjazz'"
alias radio_rc_reggae_dub="mpv -cache 10000 -cache-min 0 'http://79.111.14.76:8002/dub'"
alias radio_rc_root_reggae="mpv -cache 10000 -cache-min 0 'http://79.111.119.111:8002/rootsreggae'"
alias radio_rc_reggae_dancehall="mpv -cache 10000 -cache-min 0 'http://79.111.14.76:8002/dancehall'"
alias radio_rc_soul_blues="mpv -cache 10000 -cache-min 0 'http://79.111.14.76:8002/soulblues'"
alias radio_rc_funk="mpv -cache 10000 -cache-min 0 'http://79.111.119.111:8002/funk'"
alias radio_rc_blues="mpv -cache 10000 -cache-min 0 'http://79.120.77.11:8002/blues'"
alias radio_rc_rnb="mpv -cache 10000 -cache-min 0 'http://79.120.77.11:8002/rnb'"
alias radio_rc_mood="mpv -cache 10000 -cache-min 0 'http://79.111.14.76:8002/easylistening'"
alias radio_rc_disco="mpv -cache 10000 -cache-min 0 'http://79.120.77.11:8002/disco'"
alias radio_rc_eurodisco="mpv -cache 10000 -cache-min 0 'http://79.111.119.111:8002/eurodisco'"
alias radio_rc_intelligent_dance="mpv -cache 10000 -cache-min 0 'http://79.111.14.76:8002/idm'"
alias radio_rc_erotic="mpv -cache 10000 -cache-min 0 'http://79.120.39.202:8002/erotic'"
alias radio_psychedelic_rock="mpv -cache 10000 -cache-min 0 'https://fr1-play.adtonos.com/8102/psystation-psychedelic-rock'"
alias radio_jamaica="mpv -cache 10000 -cache-min 0 'https://stream-145.zeno.fm/2vaypn80g3quv?zs=_SW2CEgYSLq1CXR-hF46uw'"
alias radio_lyon_underground="mpv -cache 10000 -cache-min 0 'https://icecast.lyl.live/live'"
alias radio_pirate="mpv -cache 10000 -cache-min 0 'https://korna-rocks.stream.laut.fm/korna-rocks'"
alias radio_nerdcore="mpv -cache 10000 -cache-min 0 'https://stream.zeno.fm/lgvnv327nbfvv'"
alias videos='mpvpaper "*" ~/Documents/videos -o "no-audio --loop-playlist shuffle"'
# GAU to fix zsh problem
alias gau="~/go/bin/gau"
alias pwn="iwctl station wlan0 scan; sleep 1;  iwctl station wlan0 connect pwn; iwctl station wlan0 get-networks"

#vim mode
set -o vi
if [[ $TERM == xterm ]]; then TERM=xterm-256color; fi
# /bin/cat ~/.todo.md
alias todo='vim ~/.todo.md'

# Open kitty in last path
chpwd() {
      echo $PWD > ~/.last_dir
}

alias todo="vim ~/.todo.md"
cat ~/.todo.md -pp
